---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: http-mirror
  namespace: http-mirror
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
