---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: http-mirror
spec:
  #host: http-mirror-http-mirror.apps.core-ocp.lab.kemo.network
  path: /
  to:
    kind: Service
    name: http-mirror
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None